In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix as cm

In [20]:
# base weight :mask_rcnn_chips_3_090417.h5
test_1 = pd.read_csv('result/test_chips3_15.csv') # test 0917null.h5 on test
test_2 = pd.read_csv('result/test_chips3_20.csv') # similar with above 
test_3 = pd.read_csv('result/test_chips3_25_reversed.csv')# test reversed.h5 on test 
test_4 = pd.read_csv('result/test_chips3_1009.csv')# test 1009.h5 (10 epoch training on data4) ( about 80% null empty) on test
test_5 = pd.read_csv('result/test_chips3_data4_1012.csv')#test null train h5 on new generated data4 (precison 78%)
test_6 = pd.read_csv('result/test_chips3_data4_1015.csv')#test 090417.h5 on data4 (precision 58%)

In [1]:
def error_display(result,num):
    y_true = result['gt_class']
    y_pred = result['pre_class']
    cmatrix = cm(y_true,y_pred)
    
    num_finechips = sum(cmatrix[0])
    num_flawchips = len(result)-num_finechips
    num_pre_finechips = sum(cmatrix[:,0])
    num_pre_flawchips = len(result)-num_pre_finechips
    
    print('confusion matrix:\n')
    print(cmatrix)
    
    pres = []
    recs = []
    for i in range(4):
        precison = cmatrix[i,i]/sum(cmatrix[i])*100
        recall = cmatrix[i,i]/sum(cmatrix[:,i])*100
        pres.append(precison)
        recs.append(recall)
        print('precision and recall on class%d ： %d%%   %d%% \n'%(i,precison,recall))
    
    print('total validation samples num ：  %d'%len(result))
    print('mean presicion ： %d%%'%(np.mean(pres)))
    print('mean recall ： %d%%'%(np.mean(recs)))
    print('mean ap ：  %d%% '% (np.mean(result['ap'])*100))
    return 

In [6]:
error_display(test_1,1)

condusion matrix:

[[1175   42   38    8]
 [  17 1355    6    4]
 [  34    4 1884    4]
 [  22   13   10 1323]]
precision and recall on class0 ： 93%   94% 

precision and recall on class1 ： 98%   95% 

precision and recall on class2 ： 97%   97% 

precision and recall on class3 ： 96%   98% 

total validation samples num ：  5939
mean presicion ： 96%
mean recall ： 96%
mean ap ：  76% 


In [7]:
error_display(test_2,2)

condusion matrix:

[[1197   31   30    5]
 [  36 1339    5    2]
 [  49    4 1870    3]
 [  26   14   12 1316]]
precision and recall on class0 ： 94%   91% 

precision and recall on class1 ： 96%   96% 

precision and recall on class2 ： 97%   97% 

precision and recall on class3 ： 96%   99% 

total validation samples num ：  5939
mean presicion ： 96%
mean recall ： 96%
mean ap ：  75% 


In [8]:
error_display(test_3,3)

condusion matrix:

[[1233   12   14    4]
 [  85 1293    4    0]
 [  86    8 1832    0]
 [  38   21   22 1287]]
precision and recall on class0 ： 97%   85% 

precision and recall on class1 ： 93%   96% 

precision and recall on class2 ： 95%   97% 

precision and recall on class3 ： 94%   99% 

total validation samples num ：  5939
mean presicion ： 95%
mean recall ： 94%
mean ap ：  73% 


In [9]:
error_display(test_4,4)

condusion matrix:

[[1060  119   43   41]
 [ 403  236  532  211]
 [ 156  198 1313  259]
 [ 159   34  497  678]]
precision and recall on class0 ： 83%   59% 

precision and recall on class1 ： 17%   40% 

precision and recall on class2 ： 68%   55% 

precision and recall on class3 ： 49%   57% 

total validation samples num ：  5939
mean presicion ： 54%
mean recall ： 52%
mean ap ：  35% 


In [17]:
error_display(test_5,5)

condusion matrix:

[[3613  237   79   28]
 [ 138   17  128    0]
 [  63   77  214   67]
 [  17   43  148   75]]
precision and recall on class0 ： 91%   94% 

precision and recall on class1 ： 6%   4% 

precision and recall on class2 ： 50%   37% 

precision and recall on class3 ： 26%   44% 

total validation samples num ：  4944
mean presicion ： 43%
mean recall ： 45%
mean ap ：  5% 


In [18]:
error_display(test_6,6)

condusion matrix:

[[2556 1012  284  105]
 [  81   48  153    1]
 [  40   94  214   73]
 [  15   39  145   84]]
precision and recall on class0 ： 64%   94% 

precision and recall on class1 ： 16%   4% 

precision and recall on class2 ： 50%   26% 

precision and recall on class3 ： 29%   31% 

total validation samples num ：  4944
mean presicion ： 40%
mean recall ： 39%
mean ap ：  5% 
